### ISSUE TITLE
Cannot install ccGains on MAC with Python 3.7.2

### ISSUE THREAD

**Issue by mbenhalima** [probstj/ccGains#23]
I have been unable to install ccGrains on MAC with Python 3.7.2

Here are the steps I am following:
    git clone https://github.com/probstj/ccgains.git
    cd ccgains
    pip3 install .
I get the this error:

    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

Looks like an error in installing the required 'tables' module. 
I have tried to set the HDF5_DIR env variable, using --hdf5, and brew install hdf5
But nothing helped in fixing this issue. Any ideas?

**Comment by anson-vandoren** [comment]
I had the same problem with same setup, but `brew install hdf5` fixed it for me. After installing hdf5, did you try unsetting your environment variable and running `pip install .` again?

Is the error message the same after having installed hdf5 with brew?

**Comment by probstj** [comment]
Thanks Anson for your help! Mbenhalima, did it work?

**Comment by mbenhalima** [comment]
thanks @anson-vandoren  for the suggestions! this what finally worked for me:
```
brew install hdf5
brew install cairo
brew install pango
export HDF5_DIR=/usr/local/Cellar/hdf5/1.10.4/  # so the env variable should be the full path to the hdf5 package
```

**Comment by tomsnick** [comment]
I think I successfully loaded ccgains on my Linux machine but cannot get pip to work:
tomf@tomVaio:~/ccgains/ccgains$ pip install .
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
I get the same error with
tomf@tomVaio:~/ccgains/ccgains$ pip install --user .
as well as in one directory up:
tomf@tomVaio:~/ccgains$ pip install --user .
To help figure out the problem here are the directory contents:
tomf@tomVaio:~/ccgains$ dir
ccgains          COPYING      data    examples     README.md       setup.py
contributors.txt  COPYING.LESSER  docs    MANIFEST.in  run_tests.sh  tests
tomf@tomVaio:~/ccgains/ccgains$ dir
bags.py         historic_data.py  relations.py  templates
binance_util.py  __init__.py       reports.py     trades.py
I removed the ccgains directories and "git cloned" again but got the same error message with pip.  There are no obvious errors that I can see during "git clone" but here is confirmation, in case that helps determine the problem:
tomf@tomVaio:~$ git clone https://github.com/probstj/ccgains.git
Cloning into 'ccgains'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 564 (delta 57), reused 94 (delta 57), pack-reused 470
Receiving objects: 100% (564/564), 1.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (362/362), done.
Checking connectivity... done

**Comment by tomsnick** [comment]
Yikes! I don't know why my text has cross outs. Here, I paste again:

I think I successfully loaded ccgains on my Linux machine but cannot get pip to work:
tomf@tomVaio:~/ccgains/ccgains$ pip install .
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
I get the same error with
tomf@tomVaio:~/ccgains/ccgains$ pip install --user .
as well as in one directory up:
tomf@tomVaio:~/ccgains$ pip install --user .
To help figure out the problem here are the directory contents:
tomf@tomVaio:~/ccgains$ dir
ccgains          COPYING      data    examples     README.md       setup.py
contributors.txt  COPYING.LESSER  docs    MANIFEST.in  run_tests.sh  tests
tomf@tomVaio:~/ccgains/ccgains$ dir
bags.py         historic_data.py  relations.py  templates
binance_util.py  __init__.py       reports.py     trades.py
I removed the ccgains directories and "git cloned" again but got the same error message with pip.  There are no obvious errors that I can see during "git clone" but here is confirmation, in case that helps determine the problem:
tomf@tomVaio:~$ git clone https://github.com/probstj/ccgains.git
Cloning into 'ccgains'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 564 (delta 57), reused 94 (delta 57), pack-reused 470
Receiving objects: 100% (564/564), 1.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (362/362), done.
Checking connectivity... done.

**Comment by tomsnick** [comment]
I think I successfully loaded ccgains on my Linux machine but cannot get pip to work:
tomf@tomVaio:/ccgains/ccgains$ pip install .
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
I get the same error with
tomf@tomVaio:/ccgains/ccgains$ pip install --user .
as well as in one directory up:
tomf@tomVaio:/ccgains$ pip install --user .
To help figure out the problem here are the directory contents:
tomf@tomVaio:/ccgains$ dir
ccgains          COPYING      data    examples     README.md       setup.py
contributors.txt  COPYING.LESSER  docs    MANIFEST.in  run_tests.sh  tests
tomf@tomVaio:/ccgains/ccgains$ dir
bags.py         historic_data.py  relations.py  templates
binance_util.py  __init__.py       reports.py     trades.py
I removed the ccgains directories and "git cloned" again but got the same error message with pip.  There are no obvious errors that I can see during "git clone" but here is confirmation, in case that helps determine the problem:
tomf@tomVaio:$ git clone https://github.com/probstj/ccgains.git
Cloning into 'ccgains'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 564 (delta 57), reused 94 (delta 57), pack-reused 470
Receiving objects: 100% (564/564), 1.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (362/362), done.
Checking connectivity... done.
